### ISSUE TITLE
Raza

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/ijsra#11]
This could be your first ›real‹ article to edit, @jvandg .
- docx in Github (called `elephants.docx`)
- We need the figures as separate files
- name of the author, etc.

I let you set up the `.tex`-file :-)

**Comment by LukasCBossert** [comment]
document looks fine so far (see my comments in https://github.com/LukasCBossert/ijsra/commit/7bebf36ee3d5693b6c22b729e3dd22433ec01fac). 
next step would be to insert the figures - hopefully the author will send them (soon).

**Comment by LukasCBossert** [comment]
@jvandg I fixed some issues you raised in your commit (https://github.com/LukasCBossert/ijsra/commit/aa6c26a810e78a977c6a4419b91055f15ea2fbb7).

There are still some labels wrong, but I think the author can clarify that.

**Comment by LukasCBossert** [comment]
ok. We got the feedback - unfortunately it looks like a lot to re-code or checking. 
the docx-file is called `Raza_re-submitted-version.docx` and needs to be doublechecked with the tex-file. @jvandg could you take a look at it?

**Comment by jvandg** [comment]
Sure

**Comment by LukasCBossert** [comment]
perfect. thanks - I hope the changes in the new docx-file are easy to track and insert into the tex-file.

**Comment by jvandg** [comment]
@LukasCBossert could you upload the original doc file as well?

**Comment by LukasCBossert** [comment]
@jvandg see https://github.com/LukasCBossert/ijsra/commit/da1291b609eaa0a1295a8ce5b579560af244e1b1

**Comment by jvandg** [comment]
@LukasCBossert thanks

**Comment by LukasCBossert** [comment]
thanks for the work so far. let me know when you are through @jvandg then I will look into the code and do the bibliography-files

**Comment by jvandg** [comment]
sure, will do @LukasCBossert; there are quite a few significant changes, so it's going to take several days at least

**Comment by LukasCBossert** [comment]
No problem 

Von meinem iPhone gesendet

**Comment by jvandg** [comment]
@LukasCBossert is there a way to add a comment to a particular line?

**Comment by LukasCBossert** [comment]
yes, there is. but you have to make the commit first, then go to the tex-file in the browser (e.g https://github.com/LukasCBossert/ijsra/commit/be59a805fd8fb145b10bdc34f6b20300228e500a important: it has to be the file in the commit) and there is a little plus sign, when you click it a little window opens and you can make a comment. I hope that helps.

**Comment by LukasCBossert** [comment]
@jvandg I havnt checked the details, but there is still missing:

Biber warning: [289] Utils.pm:164> WARN - I didn't find a database entry for 'Alonso2014' (section 1)

Biber warning: [289] Utils.pm:164> WARN - I didn't find a database entry for 'Sidky2000' (section 1)

Biber warning: [289] Utils.pm:164> WARN - I didn't find a database entry for 'Abduallaev1995' (section 1)

Biber warning: [289] Utils.pm:164> WARN - I didn't find a database entry for 'Stewart1991' (section 1)

**Comment by jvandg** [comment]
@LukasCBossert I should say that other than copying the new reference entries from the doc into the bib, I haven't formatted them

Abduallaev should be Abdullaev - it's a typo from the doc
Stewart 1991 should be 1993 - also a typo from the doc

**Comment by LukasCBossert** [comment]
No problem and not your fault. Together we will get through this article.
Another plus for latex since those typographical errors can't happen :)


Von meinem iPhone gesendet
