### ISSUE TITLE
General things to discuss

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/ijsra#14]
@rcesaret @DevinWard @jvandg 
I just liftet the ban of pdf.
We can discuss if it is good to exchange pdf , too. 
so we might see faster the outcome of a tex-file another person did.

And we could think of making this whole repository public:
Advantage:
- we can send back the link of the pdf to the authors and there is no need of exchanges/transferring larger files
- we may find more people wanting to help

Disadvantage:
- our discussion is visible (not that I have things to hide)

**Comment by jvandg** [comment]
If you think so, I just don't know how making the whole repository public would be very useful for authors or others. I think the biggest advantage would be being able to share the pdf with the author.

**Comment by LukasCBossert** [comment]
i opened the repository for the public. as you say we can simply send the links for the pdf to the authors and they can take a look at the in GitHub.

**Comment by jvandg** [comment]
:+1:

**Comment by LukasCBossert** [comment]
@DevinWard @rcesaret @jvandg I put in the folder the `cls`-file of the template. You dont have to do anything as long as you compile the `tex-files` in the same folder. I think it is easier for testing the template and changes will be visible right away. As soon things work properly with the template I will make an upload on CTAN.

**Comment by LukasCBossert** [comment]
Does anyone feel having another round of skyping, discussing things?

**Comment by DevinWard** [comment]
Yes, I think that would be good!  I have been following along with your discussion, sorry I've been quiet.

**Comment by jvandg** [comment]
I think that would be good as well.
