### ISSUE TITLE
Pereda

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/ijsra#17]

**Comment by LukasCBossert** [comment]
completed coding now; strange page range `361-361` (https://github.com/LukasCBossert/ijsra/blob/master/2016-02/content/17Pereda.tex#L416)

now; waiting for the figures to be delivered.

**Comment by DevinWard** [comment]
Fixed, my typo, sorry!  Should have been (361-362)

**Comment by LukasCBossert** [comment]
no problem.

**Comment by DevinWard** [comment]
The question: Image copyright approval pending.

**Comment by LukasCBossert** [comment]
is it correct that there is only one figure-file @DevinWard ?

**Comment by DevinWard** [comment]
I'll find and add the other two images today, I just added the one figure because the author got it from the original publisher in high quality and I wanted to make sure I added it before I forgot.  Sorry!

**Comment by LukasCBossert** [comment]
no problem. you can add all the figures although we dont have permission for publication. we will simple use them for their dimension and turn them into a white box.
