### ISSUE TITLE
Gyngell

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/ijsra#20]

**Comment by LukasCBossert** [comment]
I fixed some errors in the bibliography-data.

I still get the error
```
Biber warning: [232] Utils.pm:164> WARN - I didn't find a database entry for 'Valla_1991' (section 1)

Biber warning: [233] Utils.pm:164> WARN - I didn't find a database entry for 'Tchernov_1999' (section 1)

Biber warning: [233] Utils.pm:164> WARN - I didn't find a database entry for 'Fletcher_1998' (section 1)
```

**Comment by LukasCBossert** [comment]
I think page 5 should be reworked - considered the many citations of Edwards.

**Comment by DevinWard** [comment]
Yeah, I made a note to myself to find those citations, but I forgot to do that before I went to bed.  As a solution to the Edwards problem, do you think one citation at the end of the paragraph with another at the beginning would be alright?

**Comment by DevinWard** [comment]
Valla_1991 should be Valla 1999, that was my typo

**Comment by DevinWard** [comment]
Tchernov_1999 should be Tchernov_1991, that again is my error.  Clearly I should not have done this so late at night. The fletcher thing is an author error.  I need to ask for that citation and for Finlayson 2013.

**Comment by LukasCBossert** [comment]
No problem at all. Mistakes happen.... 

Von meinem iPhone gesendet

**Comment by LukasCBossert** [comment]
can or should we get more precise copyright information? so far it is only author and year
@DevinWard @rcesaret @jvandg

**Comment by jvandg** [comment]
I think author/year is fine, as long as it's correct. Only issue if re-use of an item by author has not been sought - issues with re-use of images should lay with author - whichever article it is. Permitted use should be confirmed by the authors, I believe. @DevinWard @rcesaret @jvandg

**Comment by LukasCBossert** [comment]
done with this article for issue no. 2
