### ISSUE TITLE
Rownd

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/ijsra#21]
Somehow this article hasnt had an issue.

Following things are missing:

- keywords
- authors bio

could you please help to gather the missing information and paste them here? Thanks @rcesaret @DevinWard @jvandg

**Comment by jvandg** [comment]
As far as I can tell, the edits from the second review have not been implemented yet @LukasCBossert @DevinWard

**Comment by jvandg** [comment]
As far as I can tell, the edits from the second review have not been implemented yet @LukasCBossert @DevinWard

**Comment by LukasCBossert** [comment]
does anyone have the second review? who was editing it? (or was it me ???)

**Comment by jvandg** [comment]
I have a copy of it, can upload if no one has it - edits are in tracked changes.

**Comment by LukasCBossert** [comment]
done with this article for issue no. 2
