### ISSUE TITLE
issue no 2

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/ijsra#22]
please have look at it and let me know any errors

https://github.com/LukasCBossert/ijsra/blob/master/2016-02/ijsra_2016_02.pdf

**Comment by LukasCBossert** [comment]
the issue works well, besides the f**** marginnotes/IJSRAsections.... I will try to solve this - anyways, keep looking for errors.

**Comment by jvandg** [comment]
Some things

- Page 3 and 4 - revisions needed
- pg 34 - figure 1 copyright
- copyright use for figs 4 and 5 on p139 and 140?

**Comment by jvandg** [comment]
Some things

- page 3 and 4 - revisions needed
- page 34 - figure 1 copyright
- copyright use for figs 4 and 5 on pages 139 and 140?

**Comment by LukasCBossert** [comment]
thanks, I will look into it.
just to let you know. compiling the individual articles wont work anymore - but you can still edit the code in them

**Comment by LukasCBossert** [comment]
> page 3 and 4 - revisions needed

could you specify that @jvandg which pages do you mean? simple counting or the page numbers?

**Comment by jvandg** [comment]
Referring to the page numbers

**Comment by jvandg** [comment]
Oh, I meant the content on those pages

**Comment by LukasCBossert** [comment]
yes, that is what I assumed, but wasnt sure which pages :)

**Comment by LukasCBossert** [comment]
@jvandg @rcesaret @DevinWard one last round proof reading please https://github.com/LukasCBossert/ijsra/blob/master/2016-02/ijsra_2016_02.pdf

**Comment by LukasCBossert** [comment]
done!
