### ISSUE TITLE
Bruyn and Jordaan

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/ijsra#27]

**Comment by LukasCBossert** [comment]
Need affiliation and biographical information about and from the authors.

**Comment by LukasCBossert** [comment]
in the first sentence of the bio of Chirikure, Mitchell, Ndlovu, and Deacon I think we should remove the part on where they grauated from, or if we choose to keep it, to move it to the next sentence.

**Comment by LukasCBossert** [comment]
Could we add IJSRA to the section with commonly used abbreviations in the beginning? I don't think it is necessary that we repeat it.

In Peter's, response to question 2, line 4, 'he deposit' should read 'The deposit'

Also in the third and fourth question Southern Africa is spelled with a capital letter, but the title it is in a lower case (southern Africa). Peter Mitchell response to question 3,ern ca is spelled with a capital - Southern Africa, paragraph 2, line 6 - 'southern Africa'

Jeannette Deacon response to first question, end of paragraph 5 - 'southern Africa'

I think we should it should be used as Southern Africa, with the capital, throughout the document just to be consistent.

Gavin Whitelaw response to third question - line 5. We can take out Association of Southern African Professional Archaeologists and only use the abbreviation ASAPA.

**Comment by DevinWard** [comment]
I completely agree with all of that, abbreviations sound like an awesome idea :)

**Comment by LukasCBossert** [comment]
Shadreck Chirikure, is an associate professor at University of Cape Town, SA. He runs the Archaeology Materials Laboratory at UCT, the only facility dedicated to the study of African indigenous technology. He sits on the advisory board of the ‘African Archaeological Review’ and advocates practices that bring archaeological knowledge to the public (see his tedtalk on African indigenous technology).
 
Peter Mitchell is a professor of African Archaeology at University of Oxford and a honorary research fellow at the school Geography, Archaeology, and Environmental studies at the University of Witwatersrand. He is the co-editor for “Azania: Archaeological research in Africa” and is an editorial board member for several international journals. Over the years, he has conducted fieldwork in Lesotho and has raised concerns about the management of local heritage.

Janette Deacon is retired, but was a lecturer, a journal editor, a rock art specialist, and the appointed archaeologist for the National Monuments Council. Janette managed the South African Rock Art Initiative, which trained tourist guides at South African world heritage sites on the presentation and protection of rock art. In 2016 UCT conferred Janette Deacon with an honorary Doctor of Literature.
 
Ndukuyakhe Ndlovu is a senior lecturer in archaeology at the University of Pretoria, SA. He has 15 years’ experience in heritage management in South Africa, having worked for both national and provincial heritage authorities. He is also the chief editor for the South African Archaeological Bulletin and an executive member of the World Archaeological Congress.
