### ISSUE TITLE
Verezen | THE CRUMBLING WONDER

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/ijsra#29]
Files are in the github-repo now.

**Comment by LukasCBossert** [comment]
@jvandg I allowed my self to check on the file and did some corrections (no worries, you did a great job!)

So far there are these missing/wrong bibliography-entries:
>WARN - I didn't find a database entry for 'mckenzie1991' (section 1)
WARN - I didn't find a database entry for 'Mustafa and Abu-Tayeh 2011' (section 1)
WARN - I didn't find a database entry for 'maqsood 1994' (section 1)
WARN - I didn't find a database entry for 'volkwein2010' (section 1)
WARN - I didn't find a database entry for 'Delmonaco et al. in Margottini et al. 2013' (section 1)

Did you get the information needed (like bio and tables?).

**Comment by jvandg** [comment]
@LukasCBossert bio is now received, and added.

Citations added: 'mckenzie1991' from file; 'mustafa2011' from email; 'maqsood1994' fixed (space); 'volkwein2010' changed to 'volkwein2011' (authors needs to check); 'delmonaco2013' from email

Compile error: "fig. x and ??"

Author needs to send tables

**Comment by LukasCBossert** [comment]
ok, you need to commit and sync the files, then I can take a look the issues. 

Regarding the last topic: if there are initials in the name (e.g. ` D. La Bouchardiere`), write in the bib-file: ` La Bouchardiere, D.`. Then it should work

**Comment by LukasCBossert** [comment]
@jvandg this is ready for publication, or?

**Comment by jvandg** [comment]
@LukasCBossert not just yet, few things to add, shortly

**Comment by LukasCBossert** [comment]
ok, just to let you know, I changed to first line, if you want to compile you need to uncomment it.

**Comment by jvandg** [comment]
Wait, what is an uncomment?

**Comment by LukasCBossert** [comment]
to uncomment is to come from

> %\documentclass{ijsra}

to

> \documentclass{ijsra} 


==> just to remove `%` (sorry for being so teXy)

**Comment by jvandg** [comment]
Ah! I had the suspicion that was the case, but wasn't 100% sure
