### ISSUE TITLE
Koziar | A History of Central Mexican Archaeology

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/ijsra#30]

**Comment by DevinWard** [comment]
Waiting for:

- author review of proofs
- authors' biographies
- authors' email addresses
- authors to provide citations missing from .bib file but found in text

These should together.  Authors' names and abstract/keywords in Spanish have been added.

**Comment by DevinWard** [comment]
All authors' comments included, as well as their bios, affiliations and email addresses, in addition to missing citations and a Spanish-language set of keywords and abstract.  Ready for publication.
