### ISSUE TITLE
Croucher | Quantification of Interpersonal Violence

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/ijsra#31]

**Comment by DevinWard** [comment]
First run of TeX commited to GitHub.  Needs several additional bibliographic entries, and the figures won't insert into the pdf.

Citations:
Missing US Bureau of Statistics 2006 reference, and US emergency room study 1990.
Missing Klein 1999.
Missing White 2005
Missing WORD database citation.
Missing Hanawalk 1967
Missing cocknurn 1991
Missing Richards 2000
Missing Shepherd 1988
Is Gardiner 1999 or 2001?

**Comment by LukasCBossert** [comment]
@DevinWard Will take a look at it tonight.

**Comment by LukasCBossert** [comment]
@DevinWard 

I fixed it. It was mainly a wrong spelling of the filenames of the images. nothing big.

Article is fine now, besides the missing bibliography-entries:

```
WARN - I didn't find a database entry for 'klein1999' (section 1)
WARN - I didn't find a database entry for 'gardiner1999' (section 1)
WARN - I didn't find a database entry for 'white2005' (section 1)
WARN - I didn't find a database entry for 'cockburn1997' (section 1)
WARN - I didn't find a database entry for 'hanawalt1976' (section 1)
WARN - I didn't find a database entry for 'cockburn1991' (section 1)
WARN - I didn't find a database entry for 'shepherd1988' (section 1)
```

**Comment by DevinWard** [comment]
Thanks @LukasCBossert !

Just got the authors corrections to the proofs, but I still want her to cite the database she's using, so I've sent it back to get that.  Should be ready to publish soon!
