### ISSUE TITLE
Padoan | Gendering The Traces  

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/ijsra#33]

**Comment by jvandg** [comment]
sent to author for proof reading

in addition to notes in description, also waiting from author for:

- bio, affiliation, email, keywords, and an abstract if they are going to provide one

**Comment by jvandg** [comment]
Notes for fixing
- quotation marks for small passages both compile as right faced quote marks
- possible to put original publication date and republished date? I think Spivak 2010 is really Spivak 2010 [1983]? Need author to confirm whether or not this is the case, first.

**Comment by LukasCBossert** [comment]
quotations: use `\enquote{QUOTE}` or `\enquote*{QUOTE}`

republished date:
```
@book{....,
year = {2010},
origyear = {1983},
}
````
Didnt test it, but should work. You can also try `date={2010}` and `\origdate={1983}`

**Comment by jvandg** [comment]
To fix

- news publisher not showing up in references

**Comment by LukasCBossert** [comment]
Just noticed, that `fowler1977` is not cited in the text?! Nothing severe, just noticed it.

**Comment by jvandg** [comment]
Yup, waiting to hear back from author, none of the following were cited in-text, but were included in the submitted doc:

- Emerson, T. et al. 2016. ‘Paradigms Lost: Reconfiguring Cahokia's Mound
72 Beaded Burial.’ American Antiquity 81(3), 405-25.
- Fowler, M. 1977. ‘Explorations into Cahokia Archaeology.’ Illinois
Archeological Survey 7, 18-26.
- Pauketat, T. and Emerson, T. 1997. Cahokia: Domination and Ideology in
the Mississippian World. Lincoln: University of Nebraska Press, 2, 101,
187, 237, 252-3, 255, 265.
- Thompson, A. Hedman, K. and Slater, P. 2015. ‘New Dental and Isotope
Evidence of Biological Distance and Place of Origin for Mass Burial
Groups at Cahokia’s Mound 72.’ Cahokia’s Mound 72.’ American Journal of Physical Anthropology 158, 341-57.

**Comment by LukasCBossert** [comment]
strange. well, if they are not cited, they wont appear in the bibliography

**Comment by jvandg** [comment]
Great! Will take a look later.

**Comment by jvandg** [comment]
Notes
- Spivak ref not generating correctly (1983 article republished in 2010 volume - origdate does not show), and editor not showing.
- Supplementary refs added below the rest - needs to be modified
- No source was given for Schliemann figure, so just pasted the wikimedia link that matches the image.
- Could not compile - figure.sty issue still
