### ISSUE TITLE
Lakshminarayanan - Indo-Roman Trade at Arikamedu: A contextual analysis of finds from the UCL Institute of Archaeology Collection

### ISSUE THREAD

**Issue by DevinWard** [LukasCBossert/ijsra#42]
Needs images

**Comment by jvandg** [comment]
References are also needed to be added

**Comment by DevinWard** [comment]
References added, possibly secondary language abstracts?  

The list of abbreviations has been left at the end of the article, only thing left is the Tamil language script.

**Comment by LukasCBossert** [comment]
Tamil language is fixed

**Comment by LukasCBossert** [comment]
```
Biber warning: [586] Utils.pm:193> WARN - I didn't find a database entry for 'kasithan1994' (section 1)
Biber warning: [586] Utils.pm:193> WARN - I didn't find a database entry for 'kasithan1996' (section 1)
```

**Comment by DevinWard** [comment]
This is that the references are missing, or is there something wrong in the bib code?

**Comment by LukasCBossert** [comment]
This means, that the bibtexkeys used in the article are not found in the bib-file/database.

**Comment by LukasCBossert** [comment]
Found the error - typo mistake.

**Comment by DevinWard** [comment]
My fault, then, sorry!

**Comment by LukasCBossert** [comment]
no problem, I fix it.
