### ISSUE TITLE
Mwaita - Robben Island: Representation and Interpretation of the materiality of apartheid and imprisonment

### ISSUE THREAD

**Issue by DevinWard** [LukasCBossert/ijsra#44]
reference and code problems, nearly done

**Comment by LukasCBossert** [comment]
Just a question of the grammar/spelling:

<img width="849" alt="bildschirmfoto 2018-12-08 um 19 58 56" src="https://user-images.githubusercontent.com/12896078/49689609-dfaec480-fb23-11e8-8698-6d2193d015d7.png">

should it read "is enrolled" instead of "it’s enrolled" ??

**Comment by DevinWard** [comment]
It should be "is"

**Comment by LukasCBossert** [comment]
good. corrected it.


These references have not been referenced so far 
```
(Howard 1994:1; Carman 1997 in Beck et al. 2003)
```
(in the abstract). I cannot find the connected entries in the bib-file. Anyone any clue?

**Comment by DevinWard** [comment]
Beck should be Beck 2004 (that is in the bib file), but Howard is:

@article{Howard1994,
author= {Howard, P.},
journal= {International Journal of Heritage Studies},
volume= {1},
number= {1},
year={1994},
title= {The Heritage Discipline},
pages= {1-3},
}


I’m sorry I am on a computer without LaTeX, so I won’t be able to help too much.  I can try!

D

**Comment by LukasCBossert** [comment]
No problem. Got it now.
