### ISSUE TITLE
Clark - There and Back Again: Ancestor Veneration and Necromancy in Ship-Themed Scandinavian Burials

### ISSUE THREAD

**Issue by DevinWard** [LukasCBossert/ijsra#45]

**Comment by LukasCBossert** [comment]
Same goes for figure 7 and 8

**Comment by DevinWard** [comment]
I have added again figured 7 and 8, and changed the file type for figure 1 from png to jpg.  Does this help?

D

**Comment by LukasCBossert** [comment]
it will help. I looked in the `.gitignore` file and there was `*.png` listed. that means, that all the png-files have been ignored (until couple days ago). so now it will/should be fine.
