### ISSUE TITLE
Robson - For Oikos and Polis: Classical Attic Grave Reliefs as Family Monuments

### ISSUE THREAD

**Issue by DevinWard** [LukasCBossert/ijsra#47]

**Comment by DevinWard** [comment]
Something is wrong with the code in the images.  Also I need to go through and be sure that all greek words are italicized and all BC is /BC and that all 4th's are \nth{4}

**Comment by LukasCBossert** [comment]
you probably mean \BC :-)

**Comment by DevinWard** [comment]
Yes, yes I do! :P
