### ISSUE TITLE
Rivera

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/ijsra#5]

**Comment by jvandg** [comment]
I noticed that with \BC or \AD, a space always is generating after, see also Raza. I'm not sure how to solve that issue.

Not sure about the references part. There is nothing different in the bibliography-files area between source a, b, or c. It seems it will just generate like that.

**Comment by LukasCBossert** [comment]
i will need to take a look at the code.
can you make a commit and upload the pdf too?


--- gesendet von unterwegs ---

**Comment by jvandg** [comment]
By the way, I still can't generate the bibliography in the pdf yet. I'm going to read up about biblatex.

Probably best to look at the pdf that was sent out, for now.

**Comment by LukasCBossert** [comment]
the document looks fine now. Maybe it was not doing the references because your distribution has not been updated (also update package biblatex - should be version 3.6 now). Sometimes you have to delete all `Rivera.*`-files, except the `.tex`-file. and then do another round of compiling. 
I fixed the authors request about the two issues and we are good for publication with this one!
